stages:
  - test

variables:
  TAGS: "Regression"
  ENV: "prod"
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"

Test:
  stage: test
  image: docker:27
  services:
    - docker:27-dind
  before_script:
    - apk add --no-cache bash
  script:
    - ./run-docker-tests.sh --include "${TAGS}" --variable BROWSER:chrome --variable ENV:"${ENV}" testsuites/
  artifacts:
    when: always
    paths:
      - results
    expire_in: 1 week
